POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Arto",
   "number":"040-243653"
}

########

POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "",
   "number":"12345"
}

########

POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "",
   "number":""
}

########

POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Arto Hellas",
   "number":"999999"
}

########

POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Liisa Marttinen",
   "number":"999999"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Arto World",
   "number":"999999"
}

########

POST http://localhost:3001/personas
Content-Type: application/json

{
   "name": "Arto Hellas",
   "number":"999999"
}


####
POST https://phonebook-open.fly.dev/api/persons
Content-Type: application/json

{
   "name": "Arto Hellas",
   "number":"999999"
}

###
POST https://phonebook-open.fly.dev/api/persons
Content-Type: application/json

{
   "name": "Arto World",
   "number":"999999"
}

###
POST https://phonebook-open.fly.dev/api/persons
Content-Type: application/json

{
   "name": "",
   "number":"999999"
}

###
POST https://phonebook-open.fly.dev/api/persons
Content-Type: application/json

{
   "name": "Arto Work",
   "number":""
}

###
POST https://phonebook-open.fly.dev/api/perso
Content-Type: application/json

{
   "name": "Arto Work",
   "number":""
}