POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Humberto",
   "number":"12345"
}

########

POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "",
   "number":"12345"
}

########

POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "",
   "number":""
}

########

POST http://localhost:3001/api/persons
Content-Type: application/json

{
   "name": "Arto Hellas",
   "number":"999999"
}